-data-

    - iris: [sepal length,sepal width,species]
    - titanic: [pclass sibling spouse fare age gender survival]
    - tips : []
    - penguins: [species island length] widths 

columns = vectors

In [3]:
list2 = [3,4,5, 'idrees',4.5, [3,['a','b'],5]]

list2[5][1][0]

'a'

In [22]:
vectorx = [3,4,[5,6,7],3]

vectorx[2][1]

6

In [23]:
vector1 = [3,4,10]

vector2 = [2,4,10]

vector3 =[30,4,10]

sum(vector1)
len(vector1) # number of element


3

In [24]:
import numpy as np

arr = np.array(vector1)
arr

arr.max()
arr.min()
arr.mean()
arr.var() # 8.0
arr.std() # 2.82

np.float64(3.0912061651652345)

In [25]:
vector1 = [10,4,10]
vector2 = [20,4,10]
vector3 = [30,4,10]

matrix = [vector1, 
          vector2, 
          vector3] # 0 1 2

matrix = [[10,4,10],
          [20,4,10],
          [30,4,10]]

matrix

# how to check the dimensions?

 # [2,4,10] as a result
 # 2 as a result

[[10, 4, 10], [20, 4, 10], [30, 4, 10]]

In [ ]:
matrix = [vector1,vector2,vector3] #0 1 2

matrix
 #[2,4,10] as result
 #2 as result

[[3, 4, 10], [2, 4, 10], [30, 4, 10]]

In [9]:
matrix2 = [[3,4,10],
           [2,4,10]]


In [10]:
matrix2[1]

[2, 4, 10]

In [12]:
matrix2[1][0]

2

In [19]:
matrix[0][2]  # row x column

10

In [28]:

matrix[0:2][8] # row  x  column

IndexError: list index out of range

In [30]:
matrix = [10,4,10], #0
         [20,4,10], #1  #0
         [30,4,10], #2   #1
         [30,4,10]  #3

matrixarr =np.array(matrix)         

IndentationError: unexpected indent (3602153855.py, line 2)

In [31]:
type(matrixarr)

matrixarr.ndim

matrixarr[1][2]

#  1 2
matrixarr[1:3][2] # rows 

NameError: name 'matrixarr' is not defined

In [18]:
type(matrix) 

list

In [32]:
matrixarr[1][2]


NameError: name 'matrixarr' is not defined

In [33]:
matrixarr * 2 # scalar multiplication

# scaler operations with arrays
# 

matrixarr.ndim
matrixarr.shape # how many rows and columns

# rows  x  columns

NameError: name 'matrixarr' is not defined

In [34]:
# broadcastinggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg

matrixarr + 100

NameError: name 'matrixarr' is not defined

In [35]:
a = np.array([[1, 3, 5, 6],
             [2, 8, 7, 9]]
             )
b = np.array([[10], 
              [100]])

a - b
a * b
a / b
a + b

array([[ 11,  13,  15,  16],
       [102, 108, 107, 109]])

In [36]:
variance = np.array([145325, 423542, 24355, 3523456])
n = np.array([145, 542, 355, 3456])

In [37]:
((variance)**0.5) .round(2)

array([ 381.22,  650.8 ,  156.06, 1877.09])

In [38]:
covariance = np.array([145325, 423542])

n = np.array([145, 542, 355, 3456])

stdx , stdy = np.array([ 381.22,  650.8])

stdx
stdy


r = covariance/(stdx*stdy)
r

array([0.58575649, 1.70715621])

In [39]:
x = np.array([[1,4,1],
              [2,5,2]])

w = np.array([10,10,10])

w2 = np.array([[10,2,3],
              [10,2,3],
              [10,2,3]])

matmultiply_xw = np.dot(x,w)
matmultiply_xw


array([60, 90])

In [40]:
matmultiply_xw2 = np.dot(x,w2)
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])

In [41]:
matmultiply_xw2 = x @ w2
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])

In [42]:
matmultiply_xw2 = np.matmul(x,w2)
matmultiply_xw2


array([[60, 12, 18],
       [90, 18, 27]])