In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.3.5'

In [ ]:
python_list = [1,2,3,"string",6.7]


numslist = [x for x in range (10)]
print(numslist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
print(numslist*3)
print(type(numslist))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [ ]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [ ]:
print(arr1*3)
print(type(arr1))

[ 3  6  9 12 15]
<class 'numpy.ndarray'>


In [ ]:
arr1D = np.array([1,  2,  3])
print(arr1D,"\n",arr1D.ndim)

[1 2 3] 
 1


In [ ]:
arr2D = np.array([[1,  2,  3],
                  [1,  2,  3]])

print(arr2D,"\n",arr2D.ndim)

[[1 2 3]
 [1 2 3]] 
 2


In [ ]:
arr3D = np.array([[[1,  2,  3],[1,  2,  3]],
                  [[1,  2,  3],[1,  2,  3]]])

print(arr3D,"\n",arr3D.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 
 3


In [ ]:
# ndim works on objects, and checks their dimensions

print(f"dimensions are: {arr1D.ndim}")

print(f"dimensions are: {arr2D.ndim}")

print(f"dimensions are: {arr3D.ndim}")


# using np.shape method, for checking the dimensions of an array!!!
# (rows, columns)

print(f"dimensions are: {np.shape(arr1D)}")

print(f"dimensions are: {np.shape(arr2D)}")

print(f"dimensions are: {np.shape(arr3D)}")

np.ndim(arr1D)
arr1D.shape

# size, how large array is, how many elements there are in the array


# 

arr1D.dtype

dimensions are: 1
dimensions are: 2
dimensions are: 3
dimensions are: (3,)
dimensions are: (2, 3)
dimensions are: (2, 2, 3)


dtype('int64')

In [ ]:
shape1D = arr1D.ndim
shape1D

size1D = arr1D.size
size1D

size2D = arr2D.size
size2D

size3D = arr3D.size
size3D

12

In [ ]:
arr1 = np.array([1,2,3])
print(arr1)

arr2= np.array([10,20,30])
print(arr2)

print("result:", arr1%arr2)


[1 2 3]
[10 20 30]
result: [1 2 3]


In [ ]:
a=10
b=3
print(a+b) #Addition:13
print(a-b) #Subtraction:7
print(a*b) #Multiplication: 30
print(a/b) # Division:3.333
print(a//b) #Floor Division:3
print(a%b) #Modulus:1
print(a**b) #Exponentiation: 1000



13
7
30
3.3333333333333335
3
1
1000


In [ ]:
3**30

205891132094649

In [ ]:
price= np.array([4000000,3500000,25000000])
print (f"The price are: {price/1000000} million")    #scale data

The price are: [ 4.   3.5 25. ] million


-slicing
-reshaping

In [ ]:
# arrange
#easiest way to create an array quickly

range_of_numbers= np.arange(1,11)
range_of_numbers.reshape(5,2)
print(range_of_numbers)

range_example=np.arange(1,11).reshape(5,2)


print(range_example)



[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
# only list comprehension we have used
nums= [x for x in range(0,101,2)]
print(nums)



[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [ ]:
nums1=nums[0:10]  #accesing element in the list
nums1

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
nums1=nums[100:0:-1]  #accesing element in the list

arraynums = np.array(nums)
print(arraynums)

print(arraynums [0:25:-1])

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
line = np.linspace(0,1,10) # values are evenly spaced and stored in array

line


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.zeros((3,3))
np.ones((4,3))

#take in tuples of shape, and return arryas

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#random class in Numpy
#  numbers

np.random.seed(40)  #helps number reproducibility

#randomArray= np.random.rand(3,4)
#randomArray

randomArray= np.random.randint(0,100,(3,3))    #start, stop (shape)
randomArray

array([[70, 91,  7],
       [37, 56, 50],
       [65, 12, 71]], dtype=int32)

In [ ]:
change and  reshape

transform, linear algebra

In [ ]:
flatarray = randomArray.flatten()
flatarray

reshapearray = flatarray.reshape(8,2)
reshapearray

In [ ]:
#transform
reshapearray.T

NameError: name 'reshapearray' is not defined

In [ ]:
#aggregation

data = np.array([85,94,22,68,94,54,98])  #marks

#sum
#mean
#min max

print(data.sum())


#create a list of 1 to 10
#use list comprehension
#give me the addition of numbers from 1 to 10

array_idress = np.array([num for num in range (1,11)])
sum_of_array_idress= array_idress.sum()
print(sum_of_array_idress)
array_idress.mean()

#list comprehension - (number : expression)

515
55


np.float64(5.5)

In [ ]:

nums= [x for x in range(1,11)]
print(nums)

total= np.sum(nums)
print(total)




[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
55


whole thinggg::

but, we can also go,column wise

or 

row wise

In [ ]:
a_2d_matrix = np.ones((3,5))
print(a_2d_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# column wise sum

a_2d_matrix.sum(axis=0)

a_2d_matrix.sum(axis=1) #row wise sum

array([5., 5., 5.])

splitting numpy arrays

In [ ]:
#exactly same as this
dataset_array= np.arange(1,101).reshape(50,2)
print(dataset_array)

#x input-----> y output
#1-----> 2

#rows are 50

train_dataset = dataset_array[:25]  #70 rows [start:stop]


train_dataset = dataset_array[25:]  #All the rows

train_dataset


[[  1   2]
 [  3   4]
 [  5   6]
 [  7   8]
 [  9  10]
 [ 11  12]
 [ 13  14]
 [ 15  16]
 [ 17  18]
 [ 19  20]
 [ 21  22]
 [ 23  24]
 [ 25  26]
 [ 27  28]
 [ 29  30]
 [ 31  32]
 [ 33  34]
 [ 35  36]
 [ 37  38]
 [ 39  40]
 [ 41  42]
 [ 43  44]
 [ 45  46]
 [ 47  48]
 [ 49  50]
 [ 51  52]
 [ 53  54]
 [ 55  56]
 [ 57  58]
 [ 59  60]
 [ 61  62]
 [ 63  64]
 [ 65  66]
 [ 67  68]
 [ 69  70]
 [ 71  72]
 [ 73  74]
 [ 75  76]
 [ 77  78]
 [ 79  80]
 [ 81  82]
 [ 83  84]
 [ 85  86]
 [ 87  88]
 [ 89  90]
 [ 91  92]
 [ 93  94]
 [ 95  96]
 [ 97  98]
 [ 99 100]]


array([[ 51,  52],
       [ 53,  54],
       [ 55,  56],
       [ 57,  58],
       [ 59,  60],
       [ 61,  62],
       [ 63,  64],
       [ 65,  66],
       [ 67,  68],
       [ 69,  70],
       [ 71,  72],
       [ 73,  74],
       [ 75,  76],
       [ 77,  78],
       [ 79,  80],
       [ 81,  82],
       [ 83,  84],
       [ 85,  86],
       [ 87,  88],
       [ 89,  90],
       [ 91,  92],
       [ 93,  94],
       [ 95,  96],
       [ 97,  98],
       [ 99, 100]])